#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Nov 18 09:00:53 2022

@author: kenji.moua
"""
import sqlite3 as sql
connexion = sql.connect('Table')
base = connexion.cursor()


position = 1

def maison():
    pass

def rond_point():
    print("1 - fouillez dans le sac\n2 - se déplacer\n3 - parler à quelqu'un\n4 - observer les alentours")
    a = input("")
    if a == "1":
        sac()
    elif a == "2":
        marche()
    elif a == "3":
        parle()
    elif a == "4":
        cherche()
    else: rond_point()

def rencontre():
    print("un blob vous fait coucou\nil semble vous dire:\nyo Alvin, ça fait longtemps ! Bon, mec, on a besoin de toi en fait.\nJ'aurai besoin que tu me prête ton livre dont on avait parlé il y a une smeaine, se serait bien.")
    print("Première mission : retrouver le livre que le blob vous demande:\nallez dans votre maison, en face de vous.")
    print("déplacez vous:\nutilisez la touche Z")
    a = input("")
   # if a in "Zz":
       # position +=1
    print("vous voyez un sac à l'entrée de la maison ")
    maison()
    
def histoire():
    print("Tu te réveilles allongé par terre.")
    print("en face de vos est un chemin")
    print("avancer ? o/n")
    b = input("\n")
    if b == "n":
        print("vous restez là comme un con")
    elif b =="o":
        print("vous entrez dans un village")
        rencontre()
    else: histoire()
    

histoire()




def sac():
	print("Si vous souhaitez ouvrir le journal appuyez sur la touche 'j' ")
	print("Si vous souhaitez consulter vos objets appuyez sur la touche 'o' ")
	
	a = input("\n")
	if a == "j":
		def journal()
	elif a == "o":
		def objets()
			

def avancer():
	print("Si vous voulez vous déplacez appuyez sur la touche 'z' ")
	a = input("\n")
	if a == "z":
		print("")
			



